In [1]:
from joblib import load
from scipy.sparse import load_npz
import json

In [2]:
mat_path = 'projects_matrix.npz'
vect_path = 'projects_vectorizer.pkl'
keys_path = 'projects_keys.json'

matrix = load_npz(mat_path)
vectorizer = load(vect_path)
keys = json.load(open(keys_path))

In [28]:
vectorizer

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [45]:
question = "cache"

In [46]:
ques_vec = vectorizer.transform([question])

In [47]:
ques_vec

<1x774 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
cs = cosine_similarity(ques_vec, matrix)

In [50]:
cs

array([[0.19339319, 0.        , 0.13686204, 0.        , 0.04637657,
        0.        , 0.14722432]])

In [51]:
cs.ravel().argmax()

0

In [52]:
keys[0]

'cluster/gramex.yaml'

In [53]:
import yaml
l = []
vals = []

c = yaml.safe_load(open(keys[0]))
for k in ['url', 'schedule', 'import', 'log']:
    vals = c.get(k)
    l.extend([json.dumps(a) for a in vals.values()])


In [54]:
l

['{"pattern": "/$YAMLURL/bookmarks", "handler": "FileHandler", "kwargs": {"path": "$YAMLPATH/index.html", "template": true, "auth": {"login_url": "/$YAMLURL/google"}, "emails": "$EMAILS"}}',
 '{"pattern": "/$YAMLURL/", "handler": "FileHandler", "kwargs": {"path": "$YAMLPATH/landing.html", "template": true}}',
 '{"pattern": "/$YAMLURL/home", "handler": "FileHandler", "kwargs": {"path": "$YAMLPATH/index.html", "template": true, "auth": {"login_url": "/$YAMLURL/google"}, "emails": "$EMAILS"}}',
 '{"pattern": "/$YAMLURL/charts/(\\\\w+)/", "handler": "FileHandler", "kwargs": {"path": "$YAMLPATH/charts/charts.html", "template": true, "auth": {"login_url": "/$YAMLURL/google"}}}',
 '{"pattern": "/$YAMLURL/charts/([\\\\w+]/.*\\\\.png)", "handler": "FileHandler", "kwargs": {"path": "$YAMLPATH/charts/", "headers": {"Cache-Control": "public, max-age=315360000"}}, "cache": true}',
 '{"pattern": "/$YAMLURL/([\\\\w+]/.*\\\\.png)", "handler": "FileHandler", "kwargs": {"path": "$YAMLPATH/assets/img/lan

In [42]:
cs.ravel().argsort()[::-1][:3]

array([6, 5, 4])

In [18]:
mat, vect = tfidf_stuff(l)

In [28]:
q = "public"
q_vec = vect.transform([q])

In [31]:
cs = cosine_similarity(q_vec, mat)
cs.ravel().argsort()

array([ 0, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 25, 13, 11, 10,  9,
        8,  7,  3,  2,  1, 12, 26,  4,  5,  6])

In [30]:
print(cs)
print(l[6])

[[0.         0.         0.         0.         0.23761367 0.24148021
  0.27299451 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]]
{"pattern": "/$YAMLURL/(node_modules/.*)", "handler": "FileHandler", "kwargs": {"path": "$YAMLPATH/", "headers": {"Cache-Control": "public, max-age=315360000"}}, "cache": true}


In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

def tfidf_stuff(keys):
    vectorizer = TfidfVectorizer()
    matrix = vectorizer.fit_transform(keys)
    return matrix, vectorizer

In [82]:
import yaml, json
content = yaml.safe_load(open(keys[6]))

matrix_keys, vect_keys = tfidf_stuff(content.keys())
matrix_values, vect_values = tfidf_stuff(map(json.dumps, content.values()))


In [93]:
q = "formhandler"

In [94]:
q_vec_key = vect_keys.transform([q])

q_vec_values = vect_values.transform([q])

In [95]:
cs_key = cosine_similarity(q_vec_key, matrix_keys)

cs_values = cosine_similarity(q_vec_values, matrix_values)

In [96]:
print(cs_key)

[[0. 0. 0. 0. 0. 0.]]


In [97]:
print(cs_values)

[[0.         0.         0.06594657 0.         0.         0.        ]]
